import type { Meta, StoryObj } from '@storybook/react';
import Footer from '../app/components/Footer';

const meta = {
    title: 'Landing Page/Footer',
    component: Footer,
} satisfies Meta<typeof Footer>;

export default meta;

type Story = StoryObj<typeof meta>;
export const Basic: Story = {
    args: {
        title: 'Create Next App',
        description: 'Generated by create next app',
    },
};

Basic.storyName = "Default";