import type { Meta, StoryObj } from '@storybook/react';
import UserSettingsDropdown from '../app/components/UserSettingsDropdown';

const meta = {
    title: 'Landing Page/UserSettingsDropdown',
    component: UserSettingsDropdown,
} satisfies Meta<typeof UserSettingsDropdown>;

export default meta;

type Story = StoryObj<typeof meta>;
export const Basic: Story = {
    args: {
        title: 'Create Next App',
        description: 'Generated by create next app',
    },
};

Basic.storyName = "Default";